---
title: "Circular Hole Pattern"
description: "Bolt circle and radial patterns"
difficulty: Intermediate
time: "10 min"
order: 3
playground:
  exampleId: "circular-pattern"
---

Circular (bolt circle) patterns are essential for flanges, hubs, and wheels. This recipe covers the `circular_pattern` method and the `bolt_pattern` helper.

## Basic Circular Pattern

The `.circular_pattern()` method copies a part around the Z axis:

```rust
use vcad::{centered_cube, centered_cylinder};

// Create a single vent slot
let slot = centered_cube("slot", 15.0, 2.0, 10.0);

// Copy it 8 times around a 20mm radius
let vents = slot.circular_pattern(20.0, 8);

// Subtract from a disc
let disc = centered_cylinder("disc", 35.0, 3.0, 64);
let result = disc - vents;
```

<Playground exampleId="circular-pattern" />

## Bolt Pattern Helper

For bolt circles (holes around a circle), use the `bolt_pattern` helper:

```rust
use vcad::bolt_pattern;

// 6 holes on a 60mm bolt circle diameter
let holes = bolt_pattern(
    6,      // number of holes
    60.0,   // bolt circle diameter
    5.5,    // hole diameter
    10.0,   // hole depth
    32      // segments per hole
);

let flange = centered_cylinder("flange", 45.0, 8.0, 64);
let result = flange - holes;
```

<Callout type="info" title="BCD vs radius">
`bolt_pattern` uses bolt circle **diameter** (BCD), which is how manufacturers specify bolt patterns. The radius version is BCD/2.
</Callout>

## Step by Step: Flanged Hub

Let's build a complete flanged hub with a bolt pattern:

### 1. Create the hub body

```rust
let hub = centered_cylinder("hub", 15.0, 20.0, 64);
```

### 2. Add the flange

```rust
let flange = centered_cylinder("flange", 35.0, 5.0, 64)
    .translate(0.0, 0.0, -10.0);  // At bottom of hub

let body = hub + flange;
```

### 3. Add center bore

```rust
let bore = centered_cylinder("bore", 6.0, 25.0, 32);
```

### 4. Add bolt pattern

```rust
let bolts = bolt_pattern(6, 50.0, 4.5, 10.0, 24)
    .translate(0.0, 0.0, -10.0);  // In the flange
```

### 5. Combine everything

```rust
let part = body - bore - bolts;
```

## Offset Start Angle

By default, the first copy is at 0° (positive X direction). To offset:

```rust
// Start at 30° instead of 0°
let pattern = slot
    .rotate(0.0, 0.0, 30.0)  // Pre-rotate the original
    .circular_pattern(20.0, 6);
```

## Non-uniform Angular Spacing

For irregular patterns, position each element manually:

```rust
let angles = [0.0, 45.0, 180.0, 225.0];  // degrees
let hole = centered_cylinder("hole", 3.0, 10.0, 32);

let mut holes = Part::empty("holes");
for angle in angles {
    let positioned = hole
        .translate(25.0, 0.0, 0.0)  // Move to radius
        .rotate(0.0, 0.0, angle);    // Rotate into position
    holes = holes + positioned;
}
```

## Radial Slots

For radial (spoke-like) slots pointing outward:

```rust
let slot = centered_cube("slot", 20.0, 2.0, 5.0)
    .translate(15.0, 0.0, 0.0);  // Offset from center

let spokes = slot.circular_pattern(0.0, 6);  // radius=0 rotates around center
```

<Callout type="warning">
When using `circular_pattern` with radius=0, the pattern rotates around the origin. Make sure your feature is offset to the desired radius first.
</Callout>

## Complete Code: Ventilated Disc

```rust
use vcad::{centered_cube, centered_cylinder, bolt_pattern, Part};

fn ventilated_disc(
    outer_dia: f64,
    hub_dia: f64,
    thickness: f64,
    vent_count: i32,
    bolt_count: i32,
    bcd: f64,
    hole_dia: f64,
) -> Part {
    // Main disc
    let disc = centered_cylinder("disc", outer_dia / 2.0, thickness, 64);

    // Center hub boss
    let boss = centered_cylinder("boss", hub_dia / 2.0, thickness * 2.0, 32);

    // Vent slots
    let vent_radius = (outer_dia / 2.0 + hub_dia / 2.0) / 2.0;
    let vent = centered_cube("vent",
        (outer_dia - hub_dia) / 2.0 - 10.0,  // length
        3.0,                                   // width
        thickness + 2.0                        // depth
    ).translate(vent_radius, 0.0, 0.0);

    let vents = vent.circular_pattern(0.0, vent_count as usize);

    // Bolt holes
    let bolts = bolt_pattern(bolt_count as usize, bcd, hole_dia, thickness + 5.0, 24);

    // Center hole
    let center = centered_cylinder("center", 10.0, thickness * 2.0 + 5.0, 32);

    disc + boss - vents - bolts - center
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let part = ventilated_disc(100.0, 30.0, 6.0, 8, 5, 60.0, 6.5);
    part.write_stl("disc.stl")?;
    Ok(())
}
```
